version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requierements/nginx
    image: nginx:ivloisy
    ports:
      - 443:443
    restart: always
#    volumes:
#      - db_data:/var/www/html